name: modelio
title: Modelio
summary: Modelio the open source modeling environment
description: |
  Modelio is a modeling solution offering a wide range of functionality based on commonly used standards for enterprise architecture, software development and systems engineering.

  Written for developers, analysts and software and systems architects, Modelio is first and foremost a modeling environment, supporting a wide range of models and diagrams and providing many services facilitating the modeling of your architectures, such as as model consistency-checking. Support for modeling and business processes (BPMN) is integrated into Modelio. These BPMN models can be linked to other standards supported by the tool, for example UML, so as to integrate these business processes into a larger context such as an enterprise architecture.
website: https://www.modelio.org/
contact: https://github.com/anrouxel/modelio-snapcraft/issues
issues: https://github.com/anrouxel/modelio-snapcraft/issues
source-code: https://github.com/anrouxel/modelio-snapcraft
license: GPL-3.0
adopt-info: modelio
icon: snap/gui/modelio.png
version: 6.2.0

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  modelio:
    extensions: [gnome]
    command: usr/bin/modelio-wrapper
    environment:
      GTK_USE_PORTAL: 0
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media
      - browser-support
      - network
      - network-status

parts:
  modelio:
    plugin: dump
    source: https://github.com/ModelioOpenSource/Modelio/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Modelio-Open-Source-$SNAPCRAFT_PROJECT_VERSION_64_Linux.tgz
    source-type: tar
    organize:
      '*': opt/modelio/

  local-parts:
    plugin: dump
    source: ./snap/local
    source-type: local
