name: modelio
version: 5.4.1
summary: Digital logic design tool and simulator
description: |
  Digital logic design tool and simulator
icon: snap/gui/modelio.png
license: GPL-3.0

base: core24
grade: stable
confinement: strict
adopt-info: modelio
compression: lzo

platforms:
  amd64:

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

apps:
  modelio:
    extensions: [gnome]
    command: modelio
    environment:
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
      __NV_PRIME_RENDER_OFFLOAD: 1
      WEBKIT_DISABLE_COMPOSITING_MODE: 1
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - unity7
      - wayland
      - x11
      - network
      - network-bind
      - browser-support

parts:
  modelio:
    plugin: dump
    source: https://github.com/ModelioOpenSource/Modelio/releases/download/v$SNAPCRAFT_PROJECT_VERSION/modelio-open-source-$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    source-type: deb
    stage-packages:
      - libproxy1-plugin-gsettings
      - libproxy1-plugin-networkmanager
      - libatk-adaptor
      - libgtk2.0-0
      - libproxy1v5
      - libproxy-tools
      - libffi8
      - libfreetype6
      - libpng16-16t64
      - libgdk-pixbuf2.0-0
      - libsecret-1-0
      - libasound2
      - libxi6
      - libxrender1
      - libxtst6
      - libwebkit2gtk-4.0-37
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL
      ln -s usr/lib/modelio-open-source*/modelio.sh modelio
      sed -i '/"${MODELIO_PATH}\/modelio"/ s/$/ -vmargs -Duser.home=$SNAP_USER_DATA/' usr/lib/modelio-open-source*/modelio.sh