name: modelio
version: 5.4.1
summary: Digital logic design tool and simulator
description: |
  Digital logic design tool and simulator
icon: snap/gui/modelio.png
license: GPL-3.0

base: core22
grade: stable
confinement: strict
adopt-info: modelio
compression: lzo

architectures:
  - build-on: amd64

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

apps:
  modelio:
    extensions: [gnome]
    command: modelio
    environment:
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA -Dorg.eclipse.swt.browser.DefaultType=webkit -Dorg.eclipse.swt.browser.UseWebKitGTK=true
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - opengl
      - unity7
      - wayland
      - x11
      - network
      - network-bind
      - browser-support

parts:
  modelio:
    plugin: dump
    source: https://github.com/ModelioOpenSource/Modelio/releases/download/v$SNAPCRAFT_PROJECT_VERSION/modelio-open-source-$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    source-type: deb
    stage-packages:
      - libxss1
      - libgconf-2-4
      - libcurl4
      - xdg-utils
      - mariadb-client
      - mysql-client
      - postgresql-client-common
      - ibus-gtk3
      - libibus-1.0-5
      - libwebkit2gtk-4.0-37
      - libgtk-3-0
      - fonts-noto-cjk
      - fonts-noto-color-emoji
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL
      ln -s usr/lib/modelio-open-source*/modelio.sh modelio
      sed -i '/"${MODELIO_PATH}\/modelio"/ s/$/ -vmargs -Duser.home=$SNAP_USER_DATA -Dorg.eclipse.swt.browser.DefaultType=webkit -Dorg.eclipse.swt.browser.UseWebKitGTK=true/' usr/lib/modelio-open-source*/modelio.sh